# Default values for juicefs-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Overrides the chart's computed name
# nameOverride: ""
# -- Overrides the chart's computed fullname
# fullnameOverride: ""

image:
  repository: juicedata/juicefs-csi-driver
  tag: latest
  pullPolicy: ""

sidecars:
  livenessProbeImage:
    repository: quay.io/k8scsi/livenessprobe
    tag: "v1.1.0"
  nodeDriverRegistrarImage:
    repository: quay.io/k8scsi/csi-node-driver-registrar
    tag: "v1.1.0"
  csiProvisionerImage:
    repository: quay.io/k8scsi/csi-provisioner
    tag: "v1.6.0"

# for some environment without dns server and want to use /etc/hosts instead
# - ip: "127.0.0.1"
#   hostnames:
#   - "s3.juicefs.local"
#   - "redis.juicefs.local"
hostAliases: []

dnsPolicy: ClusterFirstWithHostNet
dnsConfig:
  {}
  # Example config which uses the AWS nameservers
  # dnsPolicy: "None"
  # dnsConfig:
  #   nameservers:
  #     - 169.254.169.253

serviceAccount:
  controller:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "juicefs-csi-controller-sa"

controller:
  # Default is true. This Component will control CSI Driver deployed on node
  enabled: true
  # Pod Numbers
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  # -- Grace period to allow the gateway to shutdown before it is killed
  terminationGracePeriodSeconds: 30
  # -- Affinity for gateway pods. Passed through `tpl` and, thus, to be configured as string
  # @default -- Hard node and soft zone anti-affinity
  affinity: {}
  # -- Node selector for gateway pods
  nodeSelector: {}
  # -- Tolerations for gateway pods
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  # controller service
  service:
    port: 9909
    trpe: ClusterIP


node:
  # Default is true. Node will be deployed every node to server CSI Plugin
  enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 5Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  # -- Grace period to allow the gateway to shutdown before it is killed
  terminationGracePeriodSeconds: 30
  # -- Affinity for gateway pods. Passed through `tpl` and, thus, to be configured as string
  # @default -- Hard node and soft zone anti-affinity
  affinity: {}
  # -- Node selector for gateway pods
  nodeSelector: {}
  # -- Tolerations for gateway pods
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

storageClasses:
  # StorageClass Name. It is important.
- name: juicefs-sc
  # Default is true will create a new StorageClass. It will create Secret and StorageClass used by CSI driver
  # when set false, existingStorageClass should be set.
  enabled: true
  # Default will create StorageClass, If use self create or exist, set this value.
  #   existingStorageClass: null
  # StorageClass will read a secret. Set this value if you want use exist
  #   existingSecret: null
  # Determines what volume plugin is used for provisioning PVs
  provisioner: csi.juicefs.com
  # which can be either Delete or Retain. If no reclaimPolicy is specified when a StorageClass object is created, it will default to Delete.
  reclaimPolicy: Delete
  # The volumeBindingMode field controls when volume binding and dynamic provisioning should occur.
  volumeBindingMode: Immediate

  backend:
    # The JuiceFS filesystem name.
    name: "juice"
    # Connection URL for redis database.
    # redis examples: redis://[:<PASSWORD>]@<HOST>:6379[/<DB>]
    # no auth:   redis://192.168.0.1:6379/7
    # root auth:   redis://:password@192.168.0.1:6379/7
    metaurl: ""
    # Object storage scheme, such as `s3`, `gs`, `oss`, read [juicesync README](https://github.com/juicedata/juicesync/blob/master/README.md) for the full supported list.
    storage: ""
    # accessKey: access-key
    accessKey: ""
    # secretKey: secret-key
    secretKey: ""
    # Vhost style bucket naming style.
    bucket: ""
