apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# MUST be kube-system for pods with system-cluster-critical priorityClass
namespace: kube-system
bases:
- ../../base
images:
- name: juicedata/juicefs-csi-driver
  newTag: csi-v0.3.0
